tests:
    hello:
        assertStdoutEqual: "Hello World"
        input:
            - "Hello World"
software:
    python:
        execute: ["./bld/sqlite3", "hello.db", "-cmd", "create table hello (who text); insert into hello (who) values ('[[tests]]');"]
        install:
            - apt install -y tclsh
            #- ls -l
            - mkdir bld; cd bld; ../configure; make
            #- ls -l bld/
