tests:
    hello:
        assertStdoutContains: "Balls to the Wall"
        input:
            - ""
software:
    python:
        execute: ["./bld/sqlite3", "chinook.db", "SELECT * FROM ALBUMS[[tests]]"]
        install:
            - apt install -y tclsh unzip
            #- ls -l
            - mkdir bld; cd bld; ../configure; make
            - ls -l
            - find ./ -name "*.db"
            - wget "https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip"; unzip chinook.zip
            #- ls -l bld/
