tests:
    hello:
        assertStdoutEqual: "Hello World"
        input:
            - "Hello World"
software:
    python:
        execute: ["./sqlite3", "[[tests]]"]
        install:
            - apt install -y tclsh
            - ls -l
            - mkdir bld; cd bld; ../configure; make
            - ls -l bld/
